#
./Data.sh DataOne CSDGM CDL   
./Data.sh DataOne EML CLOEBIRD
./Data.sh DataOne Dryad Dryad
./Data.sh DataOne Dryad Dryad
./Data.sh DataOne CSDGM EDACGSTORE
./Data.sh DataOne Mercury EDORA
./Data.sh DataOne EML ESA
./Data.sh DataOne EML GLEON
./Data.sh DataOne EML GOA
./Data.sh DataOne Onedcx IARC
./Data.sh DataOne EML IOE
./Data.sh DataOne EML KNB
./Data.sh DataOne EML KUBI
./Data.sh DataOne EML LTER
./Data.sh DataOne EML LTER_EUROPE
./Data.sh DataOne CSDGM NMEPSCOR
./Data.sh DataOne EML ONEShare
./Data.sh DataOne Mercury ORNLDAAC
./Data.sh DataOne EML PISCO
./Data.sh DataOne Mercury RGD
./Data.sh DataOne EML SANPARKS
./Data.sh DataOne CSDGM SEAD
./Data.sh DataOne EML TERN
./Data.sh DataOne EML TFRI
./Data.sh DataOne Onedcx US_MPC
./Data.sh DataOne EML USANPN
./Data.sh DataOne BDP USGSCSAS
./Data.sh DataOne CSDGM USGSCSAS
